image:
  storm:
    repository: timothyb89/storm
    tag: 1.0.2.4
    pullPolicy: Always
  thresh:
    repository: rbrndt/monasca-thresh
    tag: latest
    pullPolicy: Always
kafka:
  uri: kafka:9092
mysql:
  host: mysql
  port: 3306
  database: mon
  user: thresh
  password: password
persistence:
  storageClass: gluster-heketi
  enabled: false
  accessMode: ReadWriteOnce
  size: 4Gi
service:
  nimbus:
    name: nimbus
    type: ClusterIP
thresh:
  metricSpoutThreads: 2
  metricSpoutTasks: 2
zookeeper:
  uri: zookeeper:2181
  server: zookeeper
  port: 2181


