image: hoppalm/monasca-agent:latest
keystone:
  os_auth_url: http://keystone:35357/v3/
  os_username: mini-mon
  os_user_domain_name: Default
  os_password: password
  os_project_name: mini-mon
monasca_url: http://monasca:8070/v2.0