influxdb:
  ## influxdb image version
  ## ref: https://hub.docker.com/r/library/influxdb/tags/
  image:
    repo: "influxdb"
    tag: "1.1"
    pullPolicy: IfNotPresent

  ## Specify a service type
  ## NodePort is default
  ## ref: http://kubernetes.io/docs/user-guide/services/
  service:
    type: NodePort

  ## Persist data to a persitent volume
  persistence:
    enabled: false
    storageClass: gluster-heketi # Set to storage being used
    accessMode: ReadWriteOnce
    size: 100Gi

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
    limits:
      memory: 16Gi
      cpu: 8

mysql:
  ## mysql image version
  ## ref: https://hub.docker.com/r/library/mysql/tags/
  ##
  imageTag: "5.5"

  ## Specify password for root user
  ##
  ## Default: random 10 character string
  mysqlRootPassword: "secretmysql"

  ## Create a database
  ##
  mysqlDatabase: "mon"

  ## Specify an imagePullPolicy (Required)
  ## It's recommended to change this to 'Always' if the image tag is 'latest'
  ## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
  ##
  imagePullPolicy: IfNotPresent

  ## Persist data to a persitent volume
  persistence:
    enabled: false
    storageClass: gluster-heketi
    accessMode: ReadWriteOnce
    size: 10Gi

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
