name: zookeeper
image:
  repository: zookeeper
  tag: 3.3
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
persistence:
  storageClass: default
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
  purge_interval: 0
  snap_retain_count: 3
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    cpu: 1000m
    memory: 512Mi
java:
  max_ram_fraction: 2
