name: zookeeper
image:
  repository: zookeeper
  tag: 3.3
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
persistence:
  storageClass: default
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    cpu: 1000m
    memory: 512Mi
jvm_max_heap: 256