bootstrap:
  user: admin
  password: secretadmin
  project: admin
  role: admin
  service: keystone
  region: RegionOne
database_backend: mysql
image:
  pullPolicy: Always
  tag: monasca/keystone
  repository: 1.0.6
monasca:
  api_version: v2.0
  url: http://monasca:8070
mysql:
  host:  mysql
  tcp_port: 3306
  user: keystone
  password: keystone
  database: keystone
replicaCount: 1
service:
  type: ClusterIP
  name: keystone
users:
  mini_mon:
    password: password
  monasca_agent:
    password: password
  admin:
    password: secretadmin
  demo:
    password: secretadmin
  monasca_read_only:
    password: password
