apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image}}"
        ports:
        - containerPort: 8070
          name: client
        volumeMounts:
        - name: config-volume
          mountPath: /etc/monasca-api/
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "fullname" . }}