apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      {{- if .Values.side_container.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "4888"
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
            - containerPort: 8070
              name: client
        env:
            - name: LOG_LEVEL_ROOT
              value: {{ .Values.logging.log_level_root | quote }}
            - name: LOG_LEVEL_CONSOLE
              value: {{ .Values.logging.log_level_console | quote }}
            - name: KAFKA_URI
              value: {{ .Values.kafka.uri | quote }}
            - name: INFLUX_HOST
              value: "{{ .Release.Name }}-influxdb"
            - name: INFLUX_PORT
              value: {{ .Values.influxdb.port | quote }}
            - name: INFLUX_USER
              value: {{ .Values.influxdb.user | quote }}
            - name: INFLUX_PASSWORD
              value: {{ .Values.influxdb.password | quote }}
            - name: INFLUX_DB
              value: {{ .Values.influxdb.database | quote }}
            - name: MYSQL_HOST
              value: "{{ .Release.Name }}-mysql"
            - name: MYSQL_USER
              value: {{ .Values.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password | quote }}
            - name: MYSQL_DB
              value: {{ .Values.mysql.database | quote }}
            - name: KEYSTONE_IDENTITY_URI
              value: {{ .Values.keystone.identity_uri | quote }}
            - name: KEYSTONE_AUTH_URI
              value: {{ .Values.keystone.auth_uri | quote }}
            - name: KEYSTONE_ADMIN_USER
              value: {{ .Values.keystone.admin_user | quote }}
            - name: KEYSTONE_ADMIN_PASSWORD
              value: {{ .Values.keystone.admin_password | quote }}
            - name: KEYSTONE_ADMIN_TENANT
              value: {{ .Values.keystone.admin_tenant | quote }}
      {{- if .Values.side_container.enabled }}
      - name: {{ .Chart.Name }}-side-container
        image: "{{ .Values.side_container.image.repository }}:{{ .Values.side_container.image.tag }}"
        imagePullPolicy: {{ .Values.side_container.image.pullPolicy }}
        ports:
          - containerPort: 4888
            name: scrape
      {{- end }}