apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: http
    port: 8070
  selector:
    app: {{ template "fullname" . }}
