---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-storm-supervisor
  labels:
    app: {{ template "fullname" . }}-storm-supervisor
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-storm-supervisor
    spec:
      containers:
        - name: {{ template "fullname" . }}
          image: "{{ .Values.image.storm.repository }}:{{ .Values.image.storm.tag }}"
          imagePullPolicy: {{ .Values.image.storm.pullPolicy }}
          args: ["storm", "supervisor"]
          volumeMounts:
            - name: thresh-config-volume
              mountPath: /config
            - name: storm-config-volume
              mountPath: /tmpl
          env:
            - name: STORM_TEMPLATE_DIR
              value: /tmpl
            - name: STORM_CONF_DIR
              value: /conf
      volumes:
        - name: thresh-config-volume
          configMap:
            name: {{ template "fullname" . }}-thresh
        - name: storm-config-volume
          configMap:
            name: {{ template "fullname" . }}-storm
