image:
  repository: hoppalm/monasca-notification
  tag: latest
  pullPolicy: Always
replicas: 1
mysql:
  user: monapi
  password: password
  host: mysql
  database: mon
kafka:
  uri: kafka:9092
zookeeper:
  uri: zookeeper:9092
