apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-deployment
  labels:
    charts: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        target: kubernetes-api
        app: {{ template "fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image}}"
          env:
            - name: KUBERNETES_API
              value: "yes"
            - name: OS_AUTH_URL
              value: {{ .Values.keystone.os_auth_url | quote }}
            - name: OS_USERNAME
              value: {{ .Values.keystone.os_username | quote }}
            - name: MONASCA_URL
              value: {{ .Values.monasca_url | quote }}
            - name: OS_USER_DOMAIN_NAME
              value: {{ .Values.keystone.os_user_domain_name | quote }}
            - name: OS_PASSWORD
              value: {{ .Values.keystone.os_password | quote }}
            - name: OS_PROJECT_NAME
              value: {{ .Values.keystone.os_project_name | quote }}
