image:
  repository: monasca/api
  tag: master-prometheus
  pullPolicy: Always
replicaCount: 1
keystone:
  identity_uri: http://keystone:35357
  auth_uri: http://keystone:5000
  admin_password: secretadmin
  admin_user: admin
  admin_tenant: admin
mysql:
  host: mysql
  user: monapi
  password: password
  database: mon
influxdb:
  host: influxdb
  port: 8086
  user: mon_api
  password: password
  database: mon
kafka:
  uri: kafka:9092
service:
  name: monasca
  port: 8070
logging:
  log_level_root: WARN
  log_level_console: WARN
auth_disabled: false
side_container:
  enabled: true
  image:
    repository: timothyb89/monasca-sidecar
    tag: 1.0.0
    pullPolicy: Always