exporter:
  enabled: false
  image:
    repositry: rbrndt/kafka-prometheus
    tag: latest
    pullPolicy: IfNotPresent
  port: 7204
image:
  repository: monasca/kafka
  tag: 0.9.0.1-2.11-1.0.2
  pullPolicy: IfNotPresent
topic_config: segment.ms=900000,retention.ms=86400000
service:
  type: ClusterIP
  port: 9092
resources:
  requests:
    memory: 1Gi
    cpu: 250m
  limits:
    memory: 2Gi
    cpu: 2000m
persistence:
  storageClass: default
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
heap_ratio: .65
stack_size: 1024k
