apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "storm.fullname" . }}-nimbus
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.thresh.storm_name }}-nimbus"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ .Values.thresh.storm_name }}-nimbus"
    spec:
      containers:
        - name: {{ template "name" . }}-{{ .Values.thresh.storm_name }}-nimbus
          image: "{{ .Values.thresh.image.storm.repository }}:{{ .Values.thresh.image.storm.tag }}"
          imagePullPolicy: {{ .Values.thresh.image.storm.pullPolicy }}
          args: ["storm", "nimbus"]
          ports:
            - containerPort: 6627
              name: nimbus
          env:
            - name: STORM_TEMPLATE_DIR
              value: /tmpl
            - name: STORM_CONF_DIR
              value: /conf
            - name: STORM_LOCAL_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: thresh-config-volume
              mountPath: /config
            - name: storm-config-volume
              mountPath: /tmpl
            - name: data
              mountPath: /data
      volumes:
        - name: thresh-config-volume
          configMap:
            name: {{ template "thresh.fullname" . }}
        - name: storm-config-volume
          configMap:
            name: {{ template "storm.fullname" . }}
        - name: data
        {{- if .Values.thresh.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "storm.fullname" . }}-nimbus
        {{- else }}
          emptyDir: {}
        {{- end -}}