apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "grafana.fullname" . }}-init-job
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.grafana.name }}-init-job"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ .Values.grafana.name }}-init-job"
    spec:
      restartPolicy: Never
      containers:
        - name: {{ template "name" . }}-{{ .Values.grafana.name }}-init-job
          image: "{{ .Values.grafana_init.image.repository }}:{{ .Values.grafana_init.image.tag }}"
          imagePullPolicy: {{ .Values.grafana_init.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.grafana_init.log_level }}
            - name: GRAFANA_URL
              value: "http://{{ template "grafana.fullname" . }}:{{ .Values.grafana.service.port }}"
            - name: GRAFANA_USERNAME
              value: {{ .Values.grafana_init.username }}
            - name: GRAFANA_PASSWORD
              value: {{ .Values.grafana_init.password }}
            - name: DATASOURCE_URL
              value: "http://{{ template "api.fullname" . }}:{{ .Values.api.service.port }}"
