{{- if .Values.grafana.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.grafana.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ .Values.grafana.name }}"
    spec:
      containers:
        - name: {{ template "name" . }}-{{ .Values.grafana.name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          resources:
{{ toYaml .Values.grafana.resources | indent 12 }}
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
          - name: grafana-config
            mountPath: /etc/grafana
          env:
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-mysql-grafana-secret"
                  key: password
            - name: GF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-mysql-grafana-secret"
                  key: username
            - name: GF_SESSION_PROVIDER_CONFIG
              value: "$GF_DATABASE_USER:$GF_DATABASE_PASSWORD@tcp({{ .Release.Name }}-mysql:3306)/grafana"
      volumes:
        - name: grafana-config
          configMap:
            name: {{ template "grafana.fullname" . }}
{{- end}}
