{{- if .Values.grafana.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.grafana.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ .Values.grafana.name }}"
    spec:
      containers:
        - name: {{ template "name" . }}-{{ .Values.grafana.name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          resources:
{{ toYaml .Values.grafana.resources | indent 12 }}
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
          - name: grafana-config
            mountPath: /etc/grafana
          env:
            - name: GF_AUTH_KEYSTONE_AUTH_URL
            {{- if .Values.grafana.keystone.url }}
{{- include "monasca_secret_env" .Values.grafana.keystone.url | indent 14 }}
            {{- else }}
              value: "http://{{ template "keystone.fullname" . }}:{{ .Values.keystone.service.admin_port }}"
            {{- end }}
{{ include "monasca_keystone_env" .Values.grafana.keystone | indent 12 }}
            - name: GF_DATABASE_HOST
{{- include "mysql_secret_env" .Values.grafana.mysql.host | indent 14 }}
            - name: GF_DATABASE_PORT
{{- include "monasca_secret_env" .Values.grafana.mysql.port | indent 14 }}
            - name: GF_DATABASE_NAME
              value: 'mon'
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default "{{ .Release.Name }}-mysql" .Values.grafana.secretDB_name }}
                  key: {{ default "password" .Values.grafana.mysql.password.secret_key }}
            - name: GF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ default "{{ .Release.Name}}-mysql" .Values.grafana.secretDB_name }}
                  key: {{ default "username" .Values.grafana.mysql.username.secret_key }}
      volumes:
        - name: grafana-config
          configMap:
            name: {{ template "grafana.fullname" . }}
{{- end}}
