{{- if .Values.storm.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "thresh.fullname" . }}-init-job
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.storm.thresh.name }}-init-job"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ .Values.storm.thresh.name }}-init-job"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ template "name" . }}-{{ .Values.storm.thresh.name }}-init-job
          image: "{{ .Values.storm.thresh.image.repository }}:{{ .Values.storm.thresh.image.tag }}"
          imagePullPolicy: {{ .Values.storm.thresh.image.pullPolicy }}
          env:
            - name: STORM_HOSTNAME_FROM_IP
              value: "true"
            - name: STORM_WAIT_RETRIES
              value: "{{ .Values.storm.thresh.wait.retries }}"
            - name: STORM_WAIT_DELAY
              value: "{{ .Values.storm.thresh.wait.delay }}"
            - name: STORM_WAIT_TIMEOUT
              value: "{{ .Values.storm.thresh.wait.timeout }}"
            - name: ZOOKEEPER_SERVERS
              value: "{{ template "zookeeper.fullname" . }}"
            - name: STORM_ZOOKEEPER_PORT
              value: "2181"
            - name: NIMBUS_SEEDS
              value: "{{ .Release.Name }}-storm-nimbus"
            - name: METRIC_SPOUT_THREADS
              value: "{{ .Values.storm.thresh.spout.metricSpoutThreads }}"
            - name: METRIC_SPOUT_TASKS
              value: "{{ .Values.storm.thresh.spout.metricSpoutTasks }}"
            - name: EVENT_SPOUT_THREADS
              value: "{{ .Values.storm.thresh.spout.eventSpoutThreads }}"
            - name: EVENT_SPOUT_TASKS
              value: "{{ .Values.storm.thresh.spout.eventSpoutTasks }}"
            - name: EVENT_BOLT_THREADS
              value: "{{ .Values.storm.thresh.bolt.eventBoltThreads }}"
            - name: EVENT_BOLT_TASKS
              value: "{{ .Values.storm.thresh.bolt.eventBoltTasks }}"
            - name: FILTERING_BOLT_THREADS
              value: "{{ .Values.storm.thresh.bolt.filteringBoltThreads }}"
            - name: FILTERING_BOLT_TASKS
              value: "{{ .Values.storm.thresh.bolt.filteringBoltTasks }}"
            - name: ALARM_CREATION_BOLT_THREADS
              value: "{{ .Values.storm.thresh.bolt.alarmCreationBoltThreads }}"
            - name: ALARM_CREATION_BOLT_TASKS
              value: "{{ .Values.storm.thresh.bolt.alarmCreationBoltTasks }}"
            - name: AGGREGATION_BOLT_THREADS
              value: "{{ .Values.storm.thresh.bolt.aggregationBoltThreads }}"
            - name: AGGREGATION_BOLT_TASKS
              value: "{{ .Values.storm.thresh.bolt.aggregationBoltTasks }}"
            - name: THRESHOLDING_BOLT_THREADS
              value: "{{ .Values.storm.thresh.bolt.thresholdingBoltThreads }}"
            - name: THRESHOLDING_BOLT_TASKS
              value: "{{ .Values.storm.thresh.bolt.thresholdingBoltTasks }}"
            - name: KAFKA_URI
              value: "{{ .Release.Name }}-kafka:9092"
            - name: MYSQL_DB_HOST
              value: "{{ .Release.Name }}-mysql"
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_DATABASE
              value: "mon"
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-mysql-thresh-secret"
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-mysql-thresh-secret"
                  key: password
{{- end }}
