apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.zookeeper.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: client
      port: {{ .Values.zookeeper.service.port }}
    - name: peer
      port: 2888
    - name: leader-election
      port: 3888
  type: {{ .Values.zookeeper.service.type }}
  selector:
    app: {{ template "fullname" . }}
    component: "{{ .Values.zookeeper.name }}"